services:
  - type: web
    name: finance-vibes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/dashboard.py --server.headless true --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
